---
- name: Deploy Samba & configure host
  hosts:
    - samba-1.saguaroscyberhub.org
    - samba-2.saguaroscyberhub.org
  vars:
    ansible_ssh_user: cactus-admin
    ansible_ssh_private_key_file: /Users/Ethan/.ssh/saguaros-ansible-key

  tasks:
    # Installs updates
    - name: Install updates on Ubuntu
      package:
        upgrade: dist
        update_cache: true
      tags: always