---
- name: Deploy Grafana & configure host
  hosts: grafana.saguaroscyberhub.org
  vars:
    ansible_ssh_user: cactus-admin
    ansible_ssh_private_key_file: /Users/Ethan/.ssh/saguaros-ansible-key

  tasks:
    # Installs updates
    - name: Install updates on Ubuntu
      package:
        upgrade: dist
        update_cache: true
      tags: always

# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#run-grafana-via-docker-compose