---
- name: Deploy Wzauh SEIM & configure host
  hosts: wazuh.saguaroscyberhub.org
  vars:
    ansible_ssh_user: cactus-admin
    ansible_ssh_private_key_file: /Users/Ethan/.ssh/saguaros-ansible-key

  tasks:
    # Installs updates
    - name: Install updates on Ubuntu
      package:
        upgrade: dist
        update_cache: true
      tags: always

# Install guide for Wazuh over Ansible:
# https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/index.html