# -------- WIP / DO NOT USE --------
version: "3.9"  # Specify the Compose file version

services:
  service_name:  # Name of the service
    image: image_name  # Image to use for the container
    build: .  # Build the image from a Dockerfile in the current directory
    ports:
      - "host_port:container_port"  # Map host ports to container ports
    volumes:
      - "./host_directory:/container_directory"  # Mount host directories to container directories
    environment:
      - VARIABLE_NAME=value  # Set environment variables
    depends_on:
      - another_service  # Start this service after another service
    networks:
      - network_name  # Connect the service to a network

networks:
  network_name:  # Define a network